language: node_js
node_js:
- '8'
- '10'
os:
- osx
install: 
- rm package-lock.json
- npm cache clear --force
- npm i
- npm install -g codecov
- npx lerna bootstrap
script: 
- npx jest
after_success:
- codecov